version: '3.3'

services:
  app:
    build:
      context: services/app
      #target: trololo
      dockerfile: Dockerfile.development
    #command: ["/mnt/c/Program Files/maven/bin/mvn clean", "mvn dependency:resolve", "mvn verify", "mvn package", "java -jar app.jar"]
    ports:
      - "4567:4567"
    volumes:
#      - "/services/app:/code"
#      - "/services/app/target:/code/target"
      - "~/.bash_history:/.bash_history"
      - "/~/.m2/repository:/~/.m2/repository"
      - "/code/target:/services/app/target"
      - "/code:/services/app"
      - "/tmp:/tmp:delegated"