version: '3.7'

services:
  app:
    build:
      context: ./services/app
      #target: trololo
      dockerfile: Dockerfile.development
    #command: ["/mnt/c/Program Files/maven/bin/mvn clean", "mvn dependency:resolve", "mvn verify", "mvn package", "java -jar app.jar"]
    ports:
      - "4567:4567"
    volumes:
      - "~/.bash_history:/.bash_history"
      - ".:/usr/share/maven"
      - "~/.m2/repository:/~/.m2/repository"
      - "/services/app/target:/code/target"
      - "/services/app:/code"
      - "/tmp:/tmp:delegated"