version: '3.3'

services:
  app:
    #image: giantswarm/sparkexample
    build:
      context: services/app
      dockerfile: Dockerfile.development
      name: "hello"
      tag: "trololo"
    command: "bash -c" "java $JAVA_OPTS -jar target/target/app.jar"
    ports:
      - "4567:4567"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "/usr/share/maven:/usr/share/maven"
      - "~/.m2/repository:/~/.m2/repository"
      - "/services/app/target:/code/target"
      - "/services/app:/code"
      - "/tmp:/tmp:delegated"